### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by jacopeste05** [Ghost6446/Altadefinizione_downloader#2]
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by Ghost6446** [comment]
Yes sorry i delete it, create it and copy: requests
bs4 
lxml
tqdm
rich
ffmpeg-python
m3u8
cryptography==3.4.8
fake-useragent==1.1.3, and run the command again

**Comment by Ghost6446** [comment]
I add it, retry now.
